name: XConomy
version: 2.7.9
main: me.Yi.XConomy.XConomy
author: YiC
load: STARTUP
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
  xconomy:
    usage: /<command>
    description: XConomy.
    aliases: [xc]
  money:
    usage: /<command>
    description: XConomy.
  balance:
    usage: /<command>
    description: XConomy.
    aliases: [bal]
  balancetop:
    usage: /<command>
    description: XConomy.
    aliases: [baltop]
  pay:
    usage: /<command>
    description: XConomy.
  economy:
    usage: /<command>
    description: XConomy.
    aliases: [eco]
permissions:
  xconomy.user.balance:
    default: true
    children:
      xconomy.user.balance.other: true
  xconomy.user.pay:
    default: true
  xconomy.user.balancetop:
    default: true
  xconomy.admin.give:
    default: op
  xconomy.admin.take:
    default: op
  xconomy.admin.set:
    default: op